version: "3"
services:
  timemachine:
    build: "."
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
    volumes:
      - /mnt/data/time-machine:/opt/timemachine
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: rpi-timemachine
    image: yriveiro/timemachine:1.0.0
    env_file:
      - timemachine.env
